# CẤU HÌNH NGINX LÀM REVERSE PROXY TÁCH BIỆT FRONTEND VÀ BACKEND

# 1. Định cấu hình Upstream nội mạng Docker
upstream nextjs_frontend {
    server frontend_web:3001; 
}

upstream nestjs_backend {
    server backend_api:3000;
}

upstream minio_s3 {
    server minio_prod:9000;
}

upstream minio_console {
    server minio_prod:9001;
}

# ------------------------------------------------------------
# A. SERVER TRANG CHỦ (FRONTEND NEXTJS)
# Domain: 25nam.hcmutertic.com
# ------------------------------------------------------------
server {
    listen 80;
    server_name 25nam.hcmutertic.com; 

    location / {
        proxy_pass http://nextjs_frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade; # Hỗ trợ WebSockets (NextJS HMR)
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Chuyển tiếp IP thật của Client
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    server_tokens off;
}

# ------------------------------------------------------------
# B. SERVER API BACKEND (NESTJS) & MINIO
# Domain: 25nam-api.hcmutertic.com
# ------------------------------------------------------------
server {
    listen 80;
    server_name 25nam-api.hcmutertic.com; 

    # Route tới NestJS API 
    location / {
        client_max_body_size 50M; 
        
        proxy_pass http://nestjs_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # CẤU HÌNH ROUTING TỚI MINIO S3 BUCKET (Static Media)
    location /media_storage/ {
        proxy_pass http://minio_s3;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # [PRIVATE] CẤU HÌNH TRANG QUẢN TRỊ MINIO CONSOLE
    location /minio-panel/ {
        proxy_pass http://minio_console;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    server_tokens off;
}
